### ISSUE TITLE
PHP 8.0 support?

### ISSUE THREAD

**Issue by mogwa1** [ArturSierzant/OMPD#137]
Archlinux recently upgraded php to version 8.0.
I've upgraded the VM that was running OMPD perfectly fine with php 7.4 to php 8.0, but afterwards OMPD is acting up.
(I cannot completely exclude that something else during the update interfered, but none of those other package upgrades included major changes.)

I'm wondering whether php 8.0 is officially supported or tested?

I'm running OMPD from the master branch on github.  This is the apache error_log:
```
[Mon Feb 08 14:32:07.893624 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Trying to access array offset on value of type null in /srv/http/OMPD/include/initialize.inc.php on line 296, referer: http://server/
[Mon Feb 08 14:32:07.894161 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Trying to access array offset on value of type null in /srv/http/OMPD/include/initialize.inc.php on line 399, referer: http://server/
[Mon Feb 08 14:32:07.894225 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Trying to access array offset on value of type null in /srv/http/OMPD/include/initialize.inc.php on line 400, referer: http://server/
[Mon Feb 08 14:32:07.900596 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Trying to access array offset on value of type null in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 29, referer: http://server/
[Mon Feb 08 14:32:07.900658 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Trying to access array offset on value of type null in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 30, referer: http://server/
[Mon Feb 08 14:32:07.900667 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Trying to access array offset on value of type null in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 31, referer: http://server/
[Mon Feb 08 14:32:07.900695 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Undefined array key "sid" in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 112, referer: http://server/
[Mon Feb 08 14:32:07.900714 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Undefined array key "action" in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 235, referer: http://server/
[Mon Feb 08 14:32:08.498744 2021] [php:warn] [pid 454] [client <ip-address>:60251] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
[Mon Feb 08 14:32:08.498846 2021] [php:error] [pid 454] [client <ip-address>:60251] PHP Fatal error:  Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in /srv/http/OMPD/include/initialize.inc.php:239\nStack trace:\n#0 /srv/http/OMPD/include/initialize.inc.php(239): mysqli_query()\n#1 /srv/http/OMPD/cache.php(28): require_once('...')\n#2 {main}\n  thrown in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
[Mon Feb 08 14:32:08.545181 2021] [php:warn] [pid 456] [client <ip-address>:60252] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
[Mon Feb 08 14:32:08.545237 2021] [php:error] [pid 456] [client <ip-address>:60252] PHP Fatal error:  Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in /srv/http/OMPD/include/initialize.inc.php:239\nStack trace:\n#0 /srv/http/OMPD/include/initialize.inc.php(239): mysqli_query()\n#1 /srv/http/OMPD/cache.php(28): require_once('...')\n#2 {main}\n  thrown in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
```

**Comment by ArturSierzant** [comment]
Thanks for reporting this. I don't use PHP 8.0 (yet), but similar warnings (but without php errors) appeared also in PHP 7. I fixed the error from line 239 in `include/initialize.inc.php` in commit dd1012d. Please check if this helped.

**Comment by mogwa1** [comment]
Thanks for the quick reply.

I've quickly tried the latest state of the master branch, but it's still showing similar errors (see below).
Probably the first error is just hiding the remaining (potentially many?) errors.
Might be better if you debug it once you can run with PHP 8.0.

```
[Mon Feb 08 21:52:13.103433 2021] [mpm_prefork:notice] [pid 295] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1i PHP/8.0.2 configured -- resuming normal operations
[Mon Feb 08 21:52:13.103468 2021] [core:notice] [pid 295] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
[Mon Feb 08 21:52:17.926460 2021] [php:warn] [pid 297] [client <ip-address>:44130] PHP Warning:  Undefined array key "sid" in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 112
[Mon Feb 08 21:52:17.926531 2021] [php:warn] [pid 297] [client <ip-address>:44130] PHP Warning:  Undefined array key "action" in /srv/http/OMPD/skin/ompd_dark/template.header.php on line 235
[Mon Feb 08 21:52:18.232532 2021] [php:warn] [pid 298] [client <ip-address>:44134] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
[Mon Feb 08 21:52:18.232647 2021] [php:error] [pid 298] [client <ip-address>:44134] PHP Fatal error:  Uncaught TypeError: mysqli_real_escape_string(): Argument #1 ($mysql) must be of type mysqli, null given in /srv/http/OMPD/include/initialize.inc.php:907\nStack trace:\n#0 /srv/http/OMPD/include/initialize.inc.php(907): mysqli_real_escape_string()\n#1 /srv/http/OMPD/include/initialize.inc.php(250): checkDefaultFavorites()\n#2 /srv/http/OMPD/cache.php(28): require_once('...')\n#3 {main}\n  thrown in /srv/http/OMPD/include/initialize.inc.php on line 907, referer: http://server/OMPD/
[Mon Feb 08 21:52:18.238952 2021] [php:warn] [pid 303] [client <ip-address>:44142] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
[Mon Feb 08 21:52:18.239031 2021] [php:error] [pid 303] [client <ip-address>:44142] PHP Fatal error:  Uncaught TypeError: mysqli_real_escape_string(): Argument #1 ($mysql) must be of type mysqli, null given in /srv/http/OMPD/include/initialize.inc.php:907\nStack trace:\n#0 /srv/http/OMPD/include/initialize.inc.php(907): mysqli_real_escape_string()\n#1 /srv/http/OMPD/include/initialize.inc.php(250): checkDefaultFavorites()\n#2 /srv/http/OMPD/cache.php(28): require_once('...')\n#3 {main}\n  thrown in /srv/http/OMPD/include/initialize.inc.php on line 907, referer: http://server/OMPD/
[Mon Feb 08 21:52:18.453842 2021] [php:warn] [pid 300] [client <ip-address>:44138] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/
[Mon Feb 08 21:52:18.453902 2021] [php:error] [pid 300] [client <ip-address>:44138] PHP Fatal error:  Uncaught TypeError: mysqli_real_escape_string(): Argument #1 ($mysql) must be of type mysqli, null given in /srv/http/OMPD/include/initialize.inc.php:907\nStack trace:\n#0 /srv/http/OMPD/include/initialize.inc.php(907): mysqli_real_escape_string()\n#1 /srv/http/OMPD/include/initialize.inc.php(250): checkDefaultFavorites()\n#2 /srv/http/OMPD/cache.php(28): require_once('...')\n#3 {main}\n  thrown in /srv/http/OMPD/include/initialize.inc.php on line 907, referer: http://server/OMPD/
```

BTW, I can now confirm that the errors are definitely caused by PHP 8.0 and not by anything else during the system update.
I switched back and forth between 7.4 and 8.0 several times: no errors with 7.4 but with PHP 8.0 I get the errors shown above.

**Comment by ArturSierzant** [comment]
OK, another fixes in febfd35. And yes, I'll have to switch to PHP 8...

**Comment by mogwa1** [comment]
I've tried this one, and it improves a lot! I can now see the default interface show up!
The only problem is that it's not showing any information if I select an album.

I now get a lot of these errors (this is just a small selection; the error log goes on and on):
```
[Tue Feb 09 11:15:30.325218 2021] [php:error] [pid 10772] [client <ip-address>:58786] PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /srv/http/OMPD/include/library.inc.php:1731\nStack trace:\n#0/srv/http/OMPD/include/library.inc.php(1731): implode()\n#1 /srv/http/OMPD/index-view3.php(246): onmouseoverDownloadAlbum()\n#2 /srv/http/OMPD/index.php(402): require_once('...')\n#3 /srv/http/OMPD/index.php(52): view3()\n#4 {main}\n  thrown in /srv/http/OMPD/include/library.inc.php on line 1731, referer: http://server/OMPD/index.php?tileSizePHP=174
[Tue Feb 09 11:15:30.725172 2021] [php:warn] [pid 10772] [client <ip-address>:58786] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/index.php?tileSizePHP=174&action=view3album_id=gn58l9gu9i
[Tue Feb 09 11:15:30.725201 2021] [php:warn] [pid 10772] [client <ip-address>:58786] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 250, referer: http://server/OMPD/index.php?tileSizePHP=174&action=view3album_id=gn58l9gu9i
[Tue Feb 09 11:15:30.740195 2021] [php:warn] [pid 10772] [client <ip-address>:58786] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 239, referer: http://server/OMPD/index.php?tileSizePHP=174&action=view3album_id=gn58l9gu9i
[Tue Feb 09 11:15:30.740233 2021] [php:warn] [pid 10772] [client <ip-address>:58786] PHP Warning:  Undefined variable $db in /srv/http/OMPD/include/initialize.inc.php on line 250, referer: http://server/OMPD/index.php?tileSizePHP=174&action=view3&album_id=gn58l9gu9i
[Tue Feb 09 11:15:31.185200 2021] [php:warn] [pid 10772] [client <ip-address>:58786] PHP Warning:  Undefined array key "volume" in /srv/http/OMPD/ajax-evaluate-status.php on line 38, referer: http://server/OMPD/index.php?tileSizePHP=174&action=view3&album_id=gn58l9gu9i
[Tue Feb 09 11:15:31.873106 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "volume" in /srv/http/OMPD/play.php on line 2089, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:31.873140 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "track_artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:31.873149 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "Artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:31.873157 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "time" in /srv/http/OMPD/play.php on line 2128, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:31.873172 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key 1 in /srv/http/OMPD/play.php on line 2129, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:31.873182 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "audio" in /srv/http/OMPD/play.php on line 2159, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:31.873190 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "bitrate" in /srv/http/OMPD/play.php on line 2168, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870309 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "volume" in /srv/http/OMPD/play.php on line 2089, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870343 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "track_artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870352 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "Artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870359 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "time" in /srv/http/OMPD/play.php on line 2128, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870367 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key 1 in /srv/http/OMPD/play.php on line 2129, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870375 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "audio" in /srv/http/OMPD/play.php on line 2159, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:32.870383 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "bitrate" in /srv/http/OMPD/play.php on line 2168, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871443 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "volume" in /srv/http/OMPD/play.php on line 2089, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871478 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "track_artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871487 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "Artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871494 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "time" in /srv/http/OMPD/play.php on line 2128, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871502 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key 1 in /srv/http/OMPD/play.php on line 2129, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871511 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "audio" in /srv/http/OMPD/play.php on line 2159, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:33.871519 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "bitrate" in /srv/http/OMPD/play.php on line 2168, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871451 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "volume" in /srv/http/OMPD/play.php on line 2089, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871483 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "track_artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871492 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "Artist" in /srv/http/OMPD/play.php on line 2124, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871499 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "time" in /srv/http/OMPD/play.php on line 2128, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871506 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key 1 in /srv/http/OMPD/play.php on line 2129, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871514 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "audio" in /srv/http/OMPD/play.php on line 2159, referer: http://server/OMPD/playlist.php
[Tue Feb 09 11:15:34.871522 2021] [php:warn] [pid 10767] [client <ip-address>:32938] PHP Warning:  Undefined array key "bitrate" in /srv/http/OMPD/play.php on line 2168, referer: http://server/OMPD/playlist.php
```

Anyway, it's probably best that you have a look at this once you're able to run PHP 8.0.

**Comment by ArturSierzant** [comment]
Thanks for that. I'll try to figure it out.

**Comment by ArturSierzant** [comment]
In commit 89ab65f I fixed major errors - now it should work OK. I'll test it more during next few days.

**Comment by mogwa1** [comment]
I've just pulled the latest changes, and it seems that everything works now with php 8.0.
Great job!  Thanks for the fast support!

**Comment by mogwa1** [comment]
I've been using OMPD with PHP 8.0 for a couple of days now. No problems so far.
As far as I'm concerned, this issue can be closed. (Unless you want to keep it open for yourself.)

**Comment by ArturSierzant** [comment]
I've noticed one more problem - during updating empty data base. I'll fix it in next commit and then close this issue. 

Thanks again for reporting this problem - this gave me the reason to upgrade PHP on my system.

**Comment by ArturSierzant** [comment]
I've been using O!MPD with php 8 for several days and everything seems to work right. There is still a lot of php warnings, but there are no errors. I'm closing this issue - in case of any problems with compatibility with php 8 please reopen this issue.

**Comment by mogwa1** [comment]
I've also been using it with php8 for about a week.  Also no problems for me as far as I could see.
Thank you!
