### ISSUE TITLE
Latest version (git pull) gives lighttpd errors

### ISSUE THREAD

**Issue by maartenlangeveld** [ArturSierzant/OMPD#164]
Latest version (git pull) gives lighttpd errors:
```
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:PHP message: PHP Fatal error:  Uncaught ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /var/www/ompd/include/library.inc.php:273
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:Stack trace:
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#0 /var/www/ompd/include/library.inc.php(273): strpos()
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#1 /var/www/ompd/play.php(2279): findCoreTrackTitle()
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#2 /var/www/ompd/play.php(77): playlistTrack()
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#3 {main}
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:  thrown in /var/www/ompd/include/library.inc.php on line 273
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:PHP message: PHP Fatal error:  Uncaught ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /var/www/ompd/include/library.inc.php:273
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:Stack trace:
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#0 /var/www/ompd/include/library.inc.php(273): strpos()
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#1 /var/www/ompd/play.php(2279): findCoreTrackTitle()
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#2 /var/www/ompd/play.php(77): playlistTrack()
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:#3 {main}
2023-12-11 16:19:24: (mod_fastcgi.c.449) FastCGI-stderr:  thrown in /var/www/ompd/include/library.inc.php on line 273
```

**Comment by ArturSierzant** [comment]
Thanks for reporting that. I think the error is caused by a track which length of title is 1. Was one on your playlist?
In commit [e5e2765](https://github.com/ArturSierzant/OMPD/commit/e5e276553850386b7a533632e7d816d10e8e492b) I fixed it, I guess. Please check if it works in your case.

**Comment by ArturSierzant** [comment]
OK, next attempt in [aaffdeb](https://github.com/ArturSierzant/OMPD/commit/aaffdebcd2505084247891021e665590a6643a52)
For unknown reasons I can't reproduce this error at will. I use nginx and when this error appears I see in log that it begins with call like this:
`play.php?action=playlistTrack&track_id=undefined&menu=playlist&ajax=1 `
I think the reason is _track_id=**undefined**_. For now I don't known why it is _**undefined**_, but I modified playlistTrack() to handle this. Please give it a try.

**Comment by maartenlangeveld** [comment]
Hello Arthur,

Thanks for your help. Problem still occurs.
Error is logged when emtpy playlist and selecting 'Library'.

Maybe that gives some guidance?

kind regards,
Maarten

**Comment by ArturSierzant** [comment]
Yes, it was very helpful. I hope commit [62922be](https://github.com/ArturSierzant/OMPD/commit/62922be58a78d93e3c8f3c4fa0ad90dcfb1cea43) finally fixes this issue.

**Comment by maartenlangeveld** [comment]
Hi Artur,

Thanks, it helped, no errors anymore!

Maarten

**Comment by ArturSierzant** [comment]
Great :) So I'm closing this issue. Thanks again for reporting.
