### ISSUE TITLE
Import/Update stops on invalid bitmap

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#7]
Hi Artur,
initial import/update fails in case there is an error with a bitmap.
the displayed error message reads:
```
Failed to resample image /path/to/folder.jpg
```

I think this event is not that important to completely stop the import-process!?

the specific image file was [https://postimg.org/image/6rl8vp1cf/](https://postimg.org/image/6rl8vp1cf/) which seems to be a **GIF** file but the filename in my filesystem is folder**.jpg**

consider to catch this error and continue the import/update process

**Comment by ArturSierzant** [comment]
I've just corrected this - please check if it works also in your case. Update should continue and at the end there should be a link to the list of corrupted images.

**Comment by othmar52** [comment]
it seems to be fixed - thank you!
importer still freezes after a few percent (@see [#1](https://github.com/ArturSierzant/OMPD/issues/1#issuecomment-256901348)) but i think this has another reason
